### ISSUE TITLE
Inconsistency of how optional routing header should be formed

### ISSUE THREAD

**Issue by dom-white** [plcpeople/nodepccc#16]
Hi,

In the top section of the readme you state

> If you are using with a ControlLogix and possibly some CompactLogix, you likely need to specify the {routing: [0x01,0x00,0x01,0x00]} option (meaning path length 1, backplane port 0 of the ENBT module, path length 1, slot 0 of the 1756 backplane). 

But further down when you detail the API you state

``
conn.initiateConnection({port: 44818, host: '192.168.8.106' /* , routing: [0x01,0x00,0x01,0x00] */}, connected);
// Either uncomment the routing or uncomment this next line for ControlLogix/CompactLogix or if otherwise using routing	
// First 0x01, 0x00 = 1 word in the path, second 0x01, 0x00 = Port 0x01 (backplane port of Ethernet module), 0x00 = PLC is in slot 0 in chassis.  
``

So for the same routing input [0x01, 0x00, 0x01, 0x00] you initially state it will get you port 0 and slot 0, then in the second you state it will get you port 1 and slot 0.

Can you clarify which is correct interpretation of how the header should be formed please

Thanks,
Dominic

**Comment by plcpeople** [comment]
The details of the API are correct, I apologize for the error and confusion, thanks for pointing this out.

**Comment by plcpeople** [comment]
If you or others have used a path other than the default [0x01,0x00,0x01,0x00], successfully or otherwise, I am interested to hear how it went.

**Comment by dom-white** [comment]
Thanks for clearing this up. I'll try and get you some feedback regarding non default values
