### ISSUE TITLE
Add options to constructor to control log messages

### ISSUE THREAD

**Issue by gfcittolin** [plcpeople/nodepccc#19]
Hi,

I'd like to propose the same change as I've proposed to plcpeople/nodeS7#7 (yes, now I'm messing up here too :)

In summary, just add an options object to the constructor, allowing to control the verbosity of the library, maintaining backward compatibility.

**Comment by plcpeople** [comment]
Thank you for all 3 pull requests - much appreciated - good to see you found this library too :)
