### ISSUE TITLE
Bad Values ControlLogix Slot 8

### ISSUE THREAD

**Issue by AlexCastro-Prog** [plcpeople/nodepccc#34]
Hello Gus I'm trying to connect nodepccc to ControlLogix but I'm getting error. My EBNT is on slot 1 but my CPU is on Slot 8. What's the correct routing for that it?

**Comment by plcpeople** [comment]
Try routing: [0x01,0x00,0x01,0x08]

First 01,00 means there is 1 word in the path
01,08 = Backplane port of Ethernet module (01), Slot 8 of Chassis (08)

I don't think the slot of the ENBT matters when constructing the path.

**Comment by AlexCastro-Prog** [comment]
Hello Guys, Thank you so much it worked like supposed to do.

I appreciate.

**Comment by plcpeople** [comment]
Good to hear it's working I will close the issue
