### ISSUE TITLE
Serial port connectivity?

### ISSUE THREAD

**Issue by ryangriggs** [plcpeople/nodepccc#36]
Does this library support connecting to PLC serial port? such as AB Micrologix or AB SLC/5?  If so, how to write the initiateConnection() function?

Thanks for a great project!

**Comment by plcpeople** [comment]
Direct serial connections are not supported.  However, you can use a 1761-NET-ENI module connected to the serial port and initiate an IP connection to the module and this has been well tested.

**Comment by ryangriggs** [comment]
Great, thank you for a fast reply.
