### ISSUE TITLE
Connect to serial port?

### ISSUE THREAD

**Issue by ryangriggs** [plcpeople/nodepccc#39]
Is it possible to connect this library to a PLC via the serial port instead of TCP?  I have some Micrologix devices that don't have Ethernet ports, and some SLC devices that aren't near Ethernet connections - would be great if I could read/write via their serial ports.  I believe this is DF1 protocol.

Thanks!

**Comment by plcpeople** [comment]
We have successfully used this software with Micrologix and SLC 5/03 and 5/04 with a 1761-NET-ENI module.  Direct serial support is not planned, so I'll close this with the 1761-NET-ENI as the only solution.
